# Generated by Django 4.2.7 on 2025-09-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='college_name',
            field=models.CharField(blank=True, help_text='Name of your college/university', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.CharField(blank=True, help_text='Your course/degree (e.g., B.Tech CSE, MBA, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='graduation_status',
            field=models.CharField(choices=[('current', 'Current Student'), ('recent', 'Recent Graduate (0-2 years)'), ('alumni', 'Alumni (2+ years)')], default='current', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year of graduation', null=True),
        ),
    ]
