# Generated by Django 4.2.7 on 2025-10-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fas fa-tag', help_text='Font Awesome icon class (e.g., fas fa-book)', max_length=50),
        ),
    ]
